name: pytest and codecov

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-20.04
    env:
      OS: ubuntu-20.04
      PYTHON: '3.7'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: '2'
    - name: Setup python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate coverage report
      run: |
        pip install coverage
        coverage run -m pytest
    - name: Upload coverage repot to codecov.io
      uses: codecov/codecov-action@v1
      
